import { LanguageCode } from '@/core/types';

//! Language constants for client-side components
// This file contains only constants and no Prisma imports

export const LANGUAGE_MAP: Record<LanguageCode, string> = {
  en: 'English',
  ru: 'Russian',
  da: 'Danish',
  es: 'Spanish',
  fr: 'French',
  de: 'German',
  it: 'Italian',
  pt: 'Portuguese',
  zh: 'Chinese',
  ja: 'Japanese',
  ko: 'Korean',
  ar: 'Arabic',
  pl: 'Polish',
  hi: 'Hindi',
  ne: 'Nepali',
  tr: 'Turkish',
  sv: 'Swedish',
  no: 'Norwegian',
  fi: 'Finnish',
  ur: 'Urdu',
  fa: 'Persian',
  uk: 'Ukrainian',
  ro: 'Romanian',
  nl: 'Dutch',
  vi: 'Vietnamese',
  bn: 'Bengali',
  id: 'Indonesian',
} as const;

export const LANGUAGE_MAP_ARRAY = [
  { id: 'en', name: 'English' },
  { id: 'ru', name: 'Russian' },
  { id: 'da', name: 'Danish' },
  { id: 'es', name: 'Spanish' },
  { id: 'fr', name: 'French' },
  { id: 'de', name: 'German' },
  { id: 'it', name: 'Italian' },
  { id: 'pt', name: 'Portuguese' },
  { id: 'zh', name: 'Chinese' },
  { id: 'ja', name: 'Japanese' },
  { id: 'ko', name: 'Korean' },
  { id: 'ar', name: 'Arabic' },
  { id: 'pl', name: 'Polish' },
  { id: 'hi', name: 'Hindi' },
  { id: 'ne', name: 'Nepali' },
  { id: 'tr', name: 'Turkish' },
  { id: 'sv', name: 'Swedish' },
  { id: 'no', name: 'Norwegian' },
  { id: 'fi', name: 'Finnish' },
  { id: 'ur', name: 'Urdu' },
  { id: 'fa', name: 'Persian' },
  { id: 'uk', name: 'Ukrainian' },
  { id: 'ro', name: 'Romanian' },
  { id: 'nl', name: 'Dutch' },
  { id: 'vi', name: 'Vietnamese' },
  { id: 'bn', name: 'Bengali' },
  { id: 'id', name: 'Indonesian' },
] as const;
